### ISSUE TITLE
Contribution: forked version of the transport that supports ambient transactions

### ISSUE THREAD

**Issue by larsw** [rebus-org/Rebus.Msmq#1]
Hi,

 As you've probably seen from the pull requests in [Rebus.TransactionScopes](https://github.com/rebus-org/Rebus.TransactionScopes/pull/4) and [Rebus.SqlServer](https://github.com/rebus-org/Rebus.SqlServer/pull/27), I've been working on making the relevant bits aware of ambient transactions (making it possible to enlist in LTM/KTM/DTC transactions). I have a forked version of the Rebus.Msmq project, and I am wondering if you want it as a contribution:

* No thank you
* As a separate project/NuGet package in this repo
* As a separate project/NuGet package in its own repo
* Incorporated into the existing package so it can be by configuration

**Comment by mookid8000** [comment]
Ideally, I prefer "Incorporated into the existing package so it can be by configuration" because it's easier to discover for the user, and less packages to manage for maintainers.

Question is how convoluted the code will be....

Do you think you can add the feature as an opt-in thing, butstill keep the code fairly understandable?

Although: The MSMQ package is quite stable, so it's not a huge burden to maintain.... so there's still headroom, if you know what I mean, so I think I am pretty sure that it would be super-awesome if you went and added it.

😁 

Am I making myself understandable, or is this gibberish? 😁

**Comment by larsw** [comment]
You're making yourself understandable :-D

What I would suggest is that I drop the forked transport class beside the existing one, and fix the configuration/builder to either instantiate the existing one or the ambient-transaction-aware one based on the user settings. The code seems to work here, and I've done all sorts of tricks to get both the LTM/KTM/DTC to kick in, but it's quite hard to write a good test suite to cover all these, since some of it should ideally interrupt the transactions (like stopping the DTC service), so the test coverage isn't quite where it should be. It would also be nice to have someone (you?) to review the Rebus transaction-related code, so that the usage is deemed as "per design".

I'll whip something together and start a PR thread.

**Comment by mookid8000** [comment]
Fantastic! I'm looking forwarding to seeing it.

**Comment by larsw** [comment]
Just to be clear; if I incorporate it into the existing package, it will need to take a dependency on the System.Transactions assembly (it shouldn't cause any problem, since the package already targets ```net45```.

**Comment by larsw** [comment]
Reviewing my code, I see that I use ```TransactionScopeAsyncFlowOption.Enabled``` which was first available in ```net451```. I can either bump the target, or I can make the package multi-target and only support ambient transactions for ```net451``` and above. What's your preference @mookid8000 ?

As far as I know, this is needed, since the different tasks in the handling pipeline might be dispatched on different threads.

**Comment by mookid8000** [comment]
oh yeah.... well, bump the target! .NET 4.5 isn't event support by Microsoft anymore, so we might as well follow along

**Comment by dtabuenc** [comment]
Was this ever incorporated?

**Comment by mookid8000** [comment]
I don't think so.... if you're interested in picking it up from here, you're very welcome 😄
