### ISSUE TITLE
What is the format of queue to connect to remote Queue?

### ISSUE THREAD

**Issue by christranv** [rebus-org/Rebus.Msmq#4]
I tracking the source code and see that the format of connecting the local queue is **[queue_name]@[machine_name]** ex: **ProductQueue@WorkerPC**. But I try the machine name of the remote PC but it throws an error. 

Can you give me the format of queue name for connectting the remote queue?
Thank you!

**Comment by mookid8000** [comment]
What does the error say? Could you post it here, including the full exception details?

**Comment by christranv** [comment]
`SampleQueue@FormatName:Direct=TCP:[IP_ADDRESS]`
Is this the correct format for connecting to the remote queue? If yes, I will test and send the exception to you. Thanks!

**Comment by mookid8000** [comment]
When you want to send to a remote queue the format is `<queue-name>@<machine-name>`, e.g. like
```csharp
services.AddRebus(
    config => config
        .(...)
        .Routing(r => r.TypeBased().Map<MyMessage>("myservice@mymachine"))
);
```
to route all sent messages of type `MyMessage`
```csharp
await bus.Send(new MyMessage());
```
to the queue "myservice" on the machine named "mymachine".

Please post the exception details – it will make it much much easier for me to help you. 🙂

**Comment by christranv** [comment]
![image](https://user-images.githubusercontent.com/23377231/136762840-b041bfd6-b7bc-4d16-8aba-c4ff3ae5806c.png)
Sorry for my late reply, I've just backed to work on Monday. 
I follow your instruction but I meet this error. I get the computer name (machine-name) of MSMQ server on LAN network. 
I tried in local queue and it works totally fine. But in remote, it's not.
Thanks!

**Comment by mookid8000** [comment]
Ah, this is because you're trying to receive from a remote queue.

With MSMQ, you should always receive from a local queue, because that's how you get all of the benefits of MSMQ.

**Comment by christranv** [comment]
So I can not use remote queue from this Rebus.Msmq library right? I see the base of this library is Experimental.System.Messaging.

**Comment by mookid8000** [comment]
You cannot RECEIVE from remote queues.


You can SEND to remote queues just fine by mapping a type to the queue
```csharp
services.AddRebus(
    config => config
        .(...)
        .Routing(r => r.TypeBased().Map<MyMessage>("myservice@mymachine"))
);
```
and then sending to it
```csharp
await bus.Send(new MyMessage());
```
or by explicitly routing the message to it:
```csharp
await bus.Advanced.Routing.Send("myservice@mymachine", new MyMessage());
```

**Comment by christranv** [comment]
I think the best way I should do in my case is to create 2 MSMQ queues on 2 API services. Each service will send to the remote service's MSMQ queue, and receive message from their local queue.

**Comment by mookid8000** [comment]
Yes, that is EXACTLY how you should do it 🙂
